name: Update Netlify Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy changes to function directory
        run: cp -R src/data/. function/

      - name: Commit changes to netlify-branch
        run: |
          git config --global user.email "guido.apple05@gmail.com"
          git config --global user.name "Guido Rodler"
          git add .
          git commit -m "Update function directory from main branch"
          git push origin main:netlify-branch
